In [1]:
!nvidia-smi

Tue Oct 31 16:19:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   25C    P0    49W / 250W |      0MiB / 23040MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   

In [2]:
!huggingface-cli login --token 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 

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /data/user-data/sa25729/.cache/huggingface/token
Login successful


In [3]:
import transformers
import torch
from transformers import (AutoModelForCausalLM,
                          AutoModelForSequenceClassification, AutoTokenizer,
                          OPTForCausalLM)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_name = "meta-llama/Llama-2-7b-chat-hf"

tokenizer = AutoTokenizer.from_pretrained(model_name)

2023-10-31 16:19:38.913458: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-31 16:19:39.804237: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf", device_map="auto")


The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [29]:
demo_data = {'prompt': 'Answer these questions:\nQ: In Scotland a bothy/bothie is a?\nA: House\nQ: Which 2008 Western film starred Ed Harris and Viggo Mortensen as lawmen, Jeremy Irons as a rancher and Renee Zellweger as a piano-playing widow?\nA:',
  'id': 'qw_8385',
  'question': 'Which 2008 Western film starred Ed Harris and Viggo Mortensen as lawmen, Jeremy Irons as a rancher and Renee Zellweger as a piano-playing widow?',
  'answer': ['Appaloosa'],
  'generations': {'text_cleaned': [' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa',
    ' Appaloosa'],
   'text': [' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n',
    ' Appaloosa\n']}}

In [9]:
type(demo_data), demo_data.keys() ,demo_data['generations'].keys()

(dict,
 dict_keys(['prompt', 'id', 'question', 'answer', 'generations']),
 dict_keys(['text_cleaned', 'text']))

In [15]:
demo_ids = tokenizer(demo_data['prompt'], truncation=False, padding=False)

input_ids = torch.tensor(demo_ids['input_ids'])
input_ids = input_ids[None, :]
atten_mask = torch.tensor(demo_ids['attention_mask'])
atten_mask = atten_mask[None, :]

input_ids.size(), atten_mask.size()

(torch.Size([1, 76]), torch.Size([1, 76]))

In [17]:
def _generate_config(tokenizer):

#     if tokenizer.__class__.__name__ == 'LlamaTokenizerFast':
#         eos_token_id = [tokenizer.encode(_)[-1] for _ in ['.', '\n']] + [29889]  # seems to be '.' as well
#         #eos_token_id = [tokenizer(_)['input_ids'] for _ in ['\n', ',', '.']]
#     elif tokenizer.__class__.__name__ == 'GPT2Tokenizer':
#         eos_token_id = [tokenizer.encode(_)[1] for _ in ['.', '\n']]
#     else:
#         raise NotImplementedError

    eos_token_id = [tokenizer.encode(_)[-1] for _ in ['.', '\n']] + [29889]  # seems to be '.' as well
    eos_token_id += [tokenizer.eos_token_id]
    question_framing_ids = ['Question:', ' Question:', '\n', 'Answer:', ' Answer:', 'Q:']
    # Follows Kuhn et al 2023 as Llama does not have CoQA
    question_framing_ids = [[tokenizer(eos_token)['input_ids'][1]] for eos_token in question_framing_ids]
    return dict(eos_token_id=eos_token_id, bad_words_ids=question_framing_ids)

def get_generation_config(input_ids, tokenizer):
    assert len(input_ids.shape) == 2
    max_length_of_generated_sequence = 256
#     if data_name == 'triviaqa':
#         generation_config = triviaqa._generate_config(tokenizer)
#     if data_name == 'coqa':
#         generation_config = coqa._generate_config(tokenizer)
#     if data_name == 'nq_open':
#         generation_config = nq_open._generate_config(tokenizer)

    generation_config = _generate_config(tokenizer)
    generation_config['max_new_tokens'] = max_length_of_generated_sequence
    generation_config['early_stopping'] = True
    # https://jaketae.github.io/study/gpt2/#setup
    generation_config['pad_token_id'] = tokenizer.eos_token_id
    return generation_config

generation_config = get_generation_config(input_ids, tokenizer)
generation_config = transformers.GenerationConfig(**generation_config)
input_length = input_ids.shape[1]

most_likely_generations = model.generate(input_ids, attention_mask = atten_mask,
                                                    num_beams=1,
                                                    do_sample=False,
                                                    generation_config=generation_config).cpu()[0, input_length:]


In [18]:
print(most_likely_generations)
# most_likely_generations tensor([26783,   880,   471,  4796, 29889])

generated_texts = [tokenizer.decode(_, skip_special_tokens=True) for _ in most_likely_generations]
generated_texts

tensor([2401, 7003, 3628,   13])


['App', 'alo', 'osa', '\n']

In [19]:
generations = []
num_gens = 20
max_num_gen_once=4
while num_gens > 0:
    _ =  model.generate(input_ids, attention_mask=atten_mask,
                             num_beams=1, num_return_sequences=min(max_num_gen_once, num_gens),
                             do_sample=True, top_p= 1, top_k= 0,
                             temperature=1, generation_config=generation_config,
                             )
    generations.append(_[:, input_length:].cpu())
    num_gens -= len(_)
    
generations

[tensor([[2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13]]),
 tensor([[2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,    2]]),
 tensor([[2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13]]),
 tensor([[2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13],
         [2401, 7003, 3628,   13]]),
 tensor([[ 2401,  7003,  3628, 29889],
         [ 2401,  7003,  3628,    13],
         [ 2401,  7003,  3628,    13],
         [ 2401,  7003,  3628,    13]])]

In [20]:
sample_gen = generations[2][0]
generated_sample = [tokenizer.decode(_, skip_special_tokens=True) for _ in sample_gen]
generated_sample, len(sample_gen)

(['App', 'alo', 'osa', '\n'], 4)

In [21]:
sample_gen = generations[4][2]
generated_sample = [tokenizer.decode(_, skip_special_tokens=True) for _ in sample_gen]
generated_sample, len(sample_gen)

(['App', 'alo', 'osa', '\n'], 4)

In [22]:
type(generations)

list

In [23]:
generations = torch.nested.nested_tensor(generations).to_padded_tensor(tokenizer.eos_token_id)
generations = generations.reshape(-1, generations.shape[-1])[:20]
generated_texts = [tokenizer.decode(_, skip_special_tokens=True) for _ in generations]


/tmp/ipykernel_2444252/4149883299.py:1: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:177.)
  generations = torch.nested.nested_tensor(generations).to_padded_tensor(tokenizer.eos_token_id)


In [24]:
generated_texts

['Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa.',
 'Appaloosa\n',
 'Appaloosa\n',
 'Appaloosa\n']

In [25]:
# remember the data
# id 3dr23u6we5exclen4th8uq9rb42tel_0
# que What color was Cotton?
# ans white

sequences = []
curr_seq = dict(
    prompt= input_ids,
    id='3dr23u6we5exclen4th8uq9rb42tel_0',
    question= 'What color was Cotton?',
    answer= 'white',
    additional_answers= [],
)
curr_seq.update(
    dict(
        most_likely_generation_ids = most_likely_generations,
        generations_ids=generations,
    )
)
curr_seq.update(
    dict(
        most_likely_generation=tokenizer.decode(curr_seq['most_likely_generation_ids'], skip_special_tokens=True),
        generations=generated_texts,
    )
)

# curr_seq['additional_answers'] = [x[0] for x in additional_answers]

sequences.append(curr_seq)
print('sequences', len(sequences), sequences)

sequences 1 [{'prompt': tensor([[    1,   673,  1438,  5155, 29901,    13, 29984, 29901,   512, 15226,
           263,  1716, 29891, 29914, 20313,   347,   338,   263, 29973,    13,
         29909, 29901,  5619,    13, 29984, 29901,  8449, 29871, 29906, 29900,
         29900, 29947, 10504,  2706,  5810,  1127,  2155, 20349,   322,   478,
           335,  1484, 15533, 14762,   408,  4307,  1527, 29892,  5677,  6764,
          6600,   787,   408,   263,  6350,  4630,   322,   390,  1600, 29872,
           796,   514,  7872,   261,   408,   263, 11914, 29899,  1456,   292,
          9449,   340, 29973,    13, 29909, 29901]]), 'id': '3dr23u6we5exclen4th8uq9rb42tel_0', 'question': 'What color was Cotton?', 'answer': 'white', 'additional_answers': [], 'most_likely_generation_ids': tensor([2401, 7003, 3628,   13]), 'generations_ids': tensor([[ 2401,  7003,  3628,    13],
        [ 2401,  7003,  3628,    13],
        [ 2401,  7003,  3628,    13],
        [ 2401,  7003,  3628,    13],
        [

Calculate Uncertainty


In [22]:
# !pip install rouge_score
!pip install -q evaluate

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


RougeL score to get uncertainty

In [30]:
import evaluate

rouge = evaluate.load('rouge', keep_in_memory=True)
exact_match_metric = evaluate.load("exact_match")

def _compare_generated_text_to_answers(pred_txt, reference_answers):
    pred_txt = pred_txt.lstrip().lower()
    rouge_types = ['rouge1', 'rouge2', 'rougeL']
    sequence_dict = {_:0. for _ in ['exact_match'] + rouge_types}
    unique_reference_answers = set([_.lstrip().lower() for _ in reference_answers])
    for answer in unique_reference_answers:
        predictions = [pred_txt]
        print('predictions', type(predictions), predictions)
        references = [answer]
        print('references', type(references), references)
        results = exact_match_metric.compute(predictions=predictions,
                                             references=references,
                                             ignore_case=True,
                                             ignore_punctuation=True)
        sequence_dict['exact_match'] = max(results['exact_match'], sequence_dict['exact_match'])
        rouge_results = rouge.compute(predictions=predictions, references=references)
        for rouge_type in rouge_types:
            sequence_dict[rouge_type] = max(rouge_results[rouge_type], sequence_dict[rouge_type])
    return sequence_dict

all_sequences = []
all_rougeL = []
for i in range(len(demo_data['generations']['text_cleaned'])):
    sequences_rouge = _compare_generated_text_to_answers(demo_data['generations']['text_cleaned'][i], demo_data['answer'])
    print(sequences_rouge)
    all_sequences.append(sequences_rouge)
    all_rougeL.append(sequences_rouge['rougeL'])

predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, 'rouge2': 0.0, 'rougeL': 1.0}
predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, 'rouge2': 0.0, 'rougeL': 1.0}
predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, 'rouge2': 0.0, 'rougeL': 1.0}
predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, 'rouge2': 0.0, 'rougeL': 1.0}
predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, 'rouge2': 0.0, 'rougeL': 1.0}
predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, 'rouge2': 0.0, 'rougeL': 1.0}
predictions <class 'list'> ['appaloosa']
references <class 'list'> ['appaloosa']
{'exact_match': 1.0, 'rouge1': 1.0, '

In [31]:
import numpy as np
rouge_score = np.array(all_rougeL).mean()
rouge_score

1.0

Eccentricity for negtive confidence

In [24]:
import numpy as np
def jaccard_one(all_answers):
    all_answers = [set(ans.lower().split()) for ans in all_answers]
    ret = np.eye(len(all_answers))
    for i, ans_i in enumerate(all_answers):
        for j, ans_j in enumerate(all_answers[i+1:], i+1):
            ret[i,j] = ret[j,i] = len(ans_i.intersection(ans_j)) / max(len(ans_i.union(ans_j)),1)
            
    return ret

ret = jaccard_one(demo_temp['text_cleaned'])
ret.shape

(20, 20)

In [32]:
class SpetralClusteringFromLogits:
    def __init__(self,
                 affinity_mode='disagreement_w',
                 eigv_threshold=0.9,
                 cluster=True,
                 temperature=3., adjust=False) -> None:
        self.affinity_mode = affinity_mode
        self.eigv_threshold = eigv_threshold
        self.rs = 0
        self.cluster = cluster
        self.temperature = temperature
        self.adjust = adjust
        if affinity_mode == 'jaccard':
            assert self.temperature is None

    def get_laplacian(self, logits):
        W = get_affinity_mat(logits, mode=self.affinity_mode, temp=self.temperature)
        L = get_L_mat(W, symmetric=True)
        return L

    def get_eigvs(self, logits):
        L = self.get_laplacian(logits)
        return (1-get_eig(L)[0])

    def __call__(self, logits, cluster=None):
        if cluster is None: cluster = self.cluster
        L = self.get_laplacian(logits)
        if not cluster:
            return (1-get_eig(L)[0]).clip(0 if self.adjust else -1).sum()
        eigvals, eigvecs = get_eig(L, thres=self.eigv_threshold)
        k = eigvecs.shape[1]
        self.rs += 1
        kmeans = KMeans(n_clusters=k, random_state=self.rs, n_init='auto').fit(eigvecs)
        return kmeans.labels_

    def clustered_entropy(self, logits):
        from scipy.stats import entropy
        labels = self(logits, cluster=True)
        P = torch.softmax(logits, dim=-1)[:, :, 2].cpu().numpy()
        pi = find_equidist(P)
        clustered_pi = pd.Series(pi).groupby(labels).sum().values
        return entropy(clustered_pi)

    def eig_entropy(self, logits):
        W = get_affinity_mat(logits, mode=self.affinity_mode, temp=self.temperature)
        L = get_L_mat(W, symmetric=True)
        eigs = get_eig(L, eps=1e-4)[0] / W.shape[0]
        return np.exp(- (eigs * np.nan_to_num(np.log(eigs))).sum())

    def proj(self, logits):
        W = get_affinity_mat(logits, mode=self.affinity_mode, temp=self.temperature)
        L = get_L_mat(W, symmetric=True)
        eigvals, eigvecs = get_eig(L, thres=self.eigv_threshold)
        return eigvecs

    def kmeans(self, eigvecs):
        k = eigvecs.shape[1]
        self.rs += 1
        kmeans = KMeans(n_clusters=k, random_state=self.rs, n_init='auto').fit(eigvecs)
        return kmeans.labels_

def umap_visualization(eigvecs, labels):
    # perform umap visualization on the eigenvectors
    import umap
    reducer = umap.UMAP()
    embedding = reducer.fit_transform(eigvecs)
    plt.scatter(embedding[:, 0], embedding[:, 1], c=labels)
    return embedding

clusterer = SpetralClusteringFromLogits(affinity_mode='agreement_w', eigv_threshold=0.9,
                                                       cluster=False, temperature=3)


In [33]:
class ClassifyWrapper():

    def __init__(self,device='cuda') -> None:
#         self.model_name = model_name
#         self.model, self.tokenizer = models.load_model_and_tokenizer(model_name, device)
        self.tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-large-mnli")
        self.model = AutoModelForSequenceClassification.from_pretrained("roberta-large-mnli")

        pass

    @torch.no_grad()
    def _batch_pred(self, sen_1: list, sen_2: list, max_batch_size=128):
        inputs = [_[0] + ' [SEP] ' + _[1] for _ in zip(sen_1, sen_2)]
        inputs = self.tokenizer(inputs, padding=True, truncation=True)
        input_ids = torch.tensor(inputs['input_ids']).to(self.model.device)
        attention_mask = torch.tensor(inputs['attention_mask']).to(self.model.device)
        logits = []
        for st in range(0, len(input_ids), max_batch_size):
            ed = min(st + max_batch_size, len(input_ids))
            logits.append(self.model(input_ids=input_ids[st:ed],
                                attention_mask=attention_mask[st:ed])['logits'])
        return torch.cat(logits, dim=0)

    @torch.no_grad()
    def create_sim_mat_batched(self, question, answers):
        unique_ans = sorted(list(set(answers)))
        semantic_set_ids = {ans: i for i, ans in enumerate(unique_ans)}
        _rev_mapping = semantic_set_ids.copy()
        sim_mat_batch = torch.zeros((len(unique_ans), len(unique_ans),3))
        anss_1, anss_2, indices = [], [], []
        for i, ans_i in enumerate(unique_ans):
            for j, ans_j in enumerate(unique_ans):
                if i == j: continue
                anss_1.append(f"{question} {ans_i}")
                anss_2.append(f"{question} {ans_j}")
                indices.append((i,j))
        if len(indices) > 0:
            sim_mat_batch_flat = self._batch_pred(anss_1, anss_2)
            for _, (i,j) in enumerate(indices):
                sim_mat_batch[i,j] = sim_mat_batch_flat[_]
        return dict(
            mapping = [_rev_mapping[_] for _ in answers],
            sim_mat = sim_mat_batch
        )

    @torch.no_grad()
    def _pred(self, sen_1: str, sen_2: str):
        input = sen_1 + ' [SEP] ' + sen_2
        input_ids = self.tokenizer.encode(input, return_tensors='pt').to(self.model.device)

        logits = self.model(input_ids)['logits']
        # logits: [Contradiction, neutral, entailment]
        return logits

    @torch.no_grad()
    def pred_qa(self, question:str, ans_1:str, ans_2:str):
        return self._pred(f"{question} {ans_1}", f'{question} {ans_2}')

    @torch.no_grad()
    def _compare(self, question:str, ans_1:str, ans_2:str):
        pred_1 = self._pred(f"{question} {ans_1}", f'{question} {ans_2}')
        pred_2 = self._pred(f"{question} {ans_2}", f'{question} {ans_1}')
        preds = torch.concat([pred_1, pred_2], 0)

        deberta_prediction = 0 if preds.argmax(1).min() == 0 else 1
        return {'deberta_prediction': deberta_prediction,
                'prob': torch.softmax(preds,1).mean(0).cpu(),
                'pred': preds.cpu()
                }



nli_model = ClassifyWrapper(device = device)
sims = nli_model.create_sim_mat_batched(demo_data['question'], demo_data['generations']['text_cleaned'])
sims



Some weights of the model checkpoint at roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


{'mapping': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'sim_mat': tensor([[[0., 0., 0.]]])}

In [34]:
sims['sim_mat'].shape

torch.Size([1, 1, 3])

In [35]:
def recover_sim_mat_new(sim):
    sim_mat = sim['sim_mat'].clone()
    sim_mat[torch.arange(sim_mat.shape[0]), torch.arange(sim_mat.shape[0]), :] = torch.tensor([-torch.inf, -torch.inf, 100])
    mapping = sim['mapping']
    # a len(ans) x len(ans) x 3 tensor
    ret = torch.zeros((len(mapping), len(mapping), 3))
    for i, ans_i in enumerate(mapping):
        for j, ans_j in enumerate(mapping):
            ret[i,j] = torch.tensor(sim_mat[mapping[i], mapping[j]])
    return None, ret

sim_new = recover_sim_mat_new(sims)


/tmp/ipykernel_2444252/3139966089.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ret[i,j] = torch.tensor(sim_mat[mapping[i], mapping[j]])


In [36]:
sim_new[1].shape

torch.Size([20, 20, 3])

In [37]:
def get_affinity_mat(logits, mode='disagreement', temp=None, symmetric=True):
    
    W = torch.softmax(logits/temp, dim=-1)[:, :, 0]
    if symmetric:
        W = (W + W.permute(1,0))/2
        W = 1 - W

    W = W.cpu().numpy()
    W[np.arange(len(W)), np.arange(len(W))] = 1
    W = W.astype(np.float32)
    return W

def get_L_mat(W, symmetric=True):
    # compute the degree matrix from the weighted adjacency matrix
    D = np.diag(np.sum(W, axis=1))
    # compute the normalized laplacian matrix from the degree matrix and weighted adjacency matrix
    if symmetric:
        L = np.linalg.inv(np.sqrt(D)) @ (D - W) @ np.linalg.inv(np.sqrt(D))
    else:
        raise NotImplementedError()
        # compute the normalized laplacian matrix from the degree matrix and weighted adjacency matrix
        L = np.linalg.inv(D) @ (D - W)
    return L.copy()

def get_eig(L, thres=None, eps=None):
    # This function assumes L is symmetric
    # compute the eigenvalues and eigenvectors of the laplacian matrix
    if eps is not None:
        L = (1-eps) * L + eps * np.eye(len(L))
    eigvals, eigvecs = np.linalg.eigh(L)

    #eigvals, eigvecs = np.linalg.eig(L)
    #assert np.max(np.abs(eigvals.imag)) < 1e-5
    #eigvals = eigvals.real
    #idx = eigvals.argsort()
    #eigvals = eigvals[idx]
    #eigvecs = eigvecs[:,idx]

    if thres is not None:
        keep_mask = eigvals < thres
        eigvals, eigvecs = eigvals[keep_mask], eigvecs[:, keep_mask]
    return eigvals, eigvecs


temp_projected = clusterer.proj(sim_new[1]) 
temp_projected.shape
#eigenvec

(20, 1)

In [39]:
temp_projected_ = np.reshape(temp_projected, (1, 20, 1))
temp_projected_.shape, temp_projected_

((1, 20, 1),
 array([[[-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068],
         [-0.2236068]]], dtype=float32))

In [40]:
ds = np.asarray([np.linalg.norm(x -x.mean(0)[None, :],2,axis=1) for x in temp_projected_])
ds_ = np.linalg.norm(ds, 2, 1)
ds_, ds

(array([6.664002e-08], dtype=float32),
 array([[1.4901161e-08, 1.4901161e-08, 1.4901161e-08, 1.4901161e-08,
         1.4901161e-08, 1.4901161e-08, 1.4901161e-08, 1.4901161e-08,
         1.4901161e-08, 1.4901161e-08, 1.4901161e-08, 1.4901161e-08,
         1.4901161e-08, 1.4901161e-08, 1.4901161e-08, 1.4901161e-08,
         1.4901161e-08, 1.4901161e-08, 1.4901161e-08, 1.4901161e-08]],
       dtype=float32))

number_semantic_set

In [52]:
from collections import defaultdict

def _create_semantic_sets(sample):
    # https://github.com/lorenzkuhn/semantic_uncertainty
    generated_texts = sample['mapping']
    sim_mat = sample['sim_mat'].argmax(axis=-1)
    # unique_ans is also a list of integers.
    unique_generated_texts = sorted(list(set(generated_texts)))
    semantic_set_ids = {ans: i for i, ans in enumerate(unique_generated_texts)} # one id for each exact-match answer
    for i, ans_i in enumerate(unique_generated_texts):
        for j, ans_j in enumerate(unique_generated_texts[i+1:], i+1):
            if min(sim_mat[ans_i,ans_j], sim_mat[ans_j,ans_i]) > CONTRADICT:
                semantic_set_ids[ans_j] = semantic_set_ids[ans_i]

    list_of_semantic_set_ids = [semantic_set_ids[x] for x in generated_texts]
    # map according to the order of appearance
    _map = defaultdict(int)
    ret = []
    for i, ans in enumerate(list_of_semantic_set_ids):
        if ans not in _map:
            _map[ans] = len(_map)
        ret.append(_map[ans])
    return ret

num_gens = 20

sem_set = _create_semantic_sets(sims)

print('sem_set', sem_set)

get_numsets = len(set(sem_set))

print('number of semantic set:', get_numsets)


sem_set [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
number of semantic set: 1


lexical_similarity

In [9]:
org_ids = torch.tensor([    1,  9038,  2501,   263,   931, 29892,   297,   263,  2594, 29876,
          2978,   263, 17888,  3699, 29892,   727, 10600,   263,  2217,  4796,
           413, 16097,  4257, 26783,   880, 29889, 26783,   880, 10600,  1880,
           701,   297,   263,  7575, 14294,  2058,  2038,   278,  2594, 29876,
           988,   599,   310,   278,  2215,  1050, 29915, 29879, 15100, 12844,
           415, 29889,  1205, 26783,   880,  9007, 29915, 29873,  7432,   297,
           902,  2217,  3271,  2038,   278,  2594, 29876, 29892,  9360,   694,
         29889,  2296,  7258,   902, 14842,  6592,   411,   902, 16823,  1357,
           322, 29871, 29945,   916,  9883, 29879, 29889,  2178,   310,   902,
          9883, 29879,   892,   274,  1082,   322,  1652,  3096, 29891, 29892,
           763, 26783,   880, 29889,  1205,  1183,   471,   278,   871,  4796,
           697,   297,   278, 14928, 29889,   450,  1791,   310,   902,  9883,
         29879,   892,   599, 24841,   411,  9560,  4796,   260,  4087, 10076,
          5547,   763, 26783,   880, 29915, 29879, 16823,  1357, 29889, 28265,
          1422,  1754, 26783,   880,  3755, 14610, 29889,  2296,  4049, 20024,
          1183,  5148,   763,   278,  1791,   310,   902,  3942, 29889,  1105,
           697,  2462, 29892,   746, 26783,   880,  1476,   263,   508,   310,
           278,  2030,  2215,  1050, 29915, 29879, 24841, 10675, 29892,  1183,
          1304,   372,   304, 10675,  8735,   763,   963, 29889,  1932,   902,
         16823,  1357,   322,  9883, 29879,  1476,   902,   896,  4687,   425,
         29700, 29889, 29871,    13,    13, 29908,  5618,   526,   366,  2599,
         29892, 26783,   880, 29973,  3850, 29871,    13,    13, 29908, 29902,
           871,  5131,   304,   367,   901,   763,   366,  1642, 29871,    13,
            13, 29907,   327,   880, 29915, 29879, 16823,  1357, 14051,  2580,
           902,  3700,   373, 26783,   880, 29915, 29879,   322,  1497,   376,
          9048, 26783,   880, 29892,   541,   596,  3261,   338,   577,  5051,
           322,  4266, 29892,   763,   366, 29889,  1334,   723,  2360,   864,
           366,   304,   367,   738,   916,   982,  1642,  1126,   411,   393,
         29892, 26783,   880, 29915, 29879, 16823,  1357, 18691,   902,   701,
           322, 13700,   902,   964,   263,  4802, 20968,   310,  4094, 29889,
          1932, 26783,   880,  2996,   714,  1183,   471,  8735,  1449, 29889,
          2439,  9883, 29879,   301, 17840,   902,  3700,  2745, 26783,   880,
         29915, 29879,  3261,   471,   599,   599, 15589, 29889, 29871,    13,
            13, 29908, 10310, 29915, 29873,  3926,   437,   393,  1449, 29892,
         26783,   880,  3850,   896,   599, 10680, 29889,   376,  9190,   931,
           366,  1795,  4473,   701,   393,  5051,  4796,  3261,   310, 15850,
           322,   591,  7656, 29915, 29873,   864,   393,  3850, 29871,    13,
            13, 11760, 26783,   880,  2714, 29892,   376, 29902,  1735,   590,
          3458, 29889,   306,   763,  1641,  4266,  1642,   660, 29901,  1724,
          2927,   471, 26783,   880, 29973,   319, 29901])


In [10]:
org_ids.size()

torch.Size([397])